services:
  database:
    image: postgres:15-alpine
    container_name: url_shortener_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "url_shortener"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:latest
    container_name: url_shortener_cache
    ports:
      - "6379:6379"

volumes:
  postgres-data:
